{% set name = "streamlit-image-coordinates" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3c6657df55ad48ba0bc62db4ca4374f762ada6595f390f4ca6fecf18e0a350b4

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    # Upstream [build] requires: uv-build >=0.8.4,<0.9.0
    - uv-build >=0.8.4,<0.9.0             # [py<314]
    # For py314 we have only uv-build 0.9.7
    - uv-build >=0.8.4,<0.9.7             # [py>=314]
  run:
    - python
    - streamlit >=1.34

test:
  imports:
    - streamlit_image_coordinates
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
  requires:
    - pip
    - pillow
    - numpy

about:
  home: https://github.com/blackary/streamlit-image-coordinates
  dev_url: https://github.com/blackary/streamlit-image-coordinates
  doc_url: https://github.com/blackary/streamlit-image-coordinates/blob/main/README.md
  summary: Streamlit component that displays an image and returns the coordinates when you click on it
  description: |
    Streamlit component that displays an image and returns the coordinates when you click on it
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - ELundby45
